### ISSUE TITLE
TypeError: options argument must be an object

### ISSUE THREAD

**Issue by rggjan** [DVSoftware/ps4player#4]
When trying to open a file, I get this error:

GET /play/?path=...&subtitle=&start=0 500 4.088 ms - 1075
TypeError: options argument must be an object
    at normalizeSpawnArguments (child_process.js:968:11)
    at Object.exports.spawn (child_process.js:991:38)
    at /home/rggjan/linux/ps4player/server.js:125:19
    at callbacks (/home/rggjan/linux/ps4player/node_modules/express/lib/router/index.js:164:37)
    at param (/home/rggjan/linux/ps4player/node_modules/express/lib/router/index.js:138:11)
    at pass (/home/rggjan/linux/ps4player/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/home/rggjan/linux/ps4player/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/home/rggjan/linux/ps4player/node_modules/express/lib/router/index.js:33:10)
    at next (/home/rggjan/linux/ps4player/node_modules/express/node_modules/connect/lib/proto.js:174:15)
    at Object.cookieSession [as handle](/home/rggjan/linux/ps4player/node_modules/express/node_modules/connect/lib/middleware/cookieSession.js:121:5)
^C

**Comment by blerest** [comment]
+1
